### ISSUE TITLE
Light Glitches

### ISSUE THREAD

**Issue by benny57358** [lobby417/deathaura-builds#3]
At certain camera angles, the game shows a light "aura" type glitch
![capture](https://cloud.githubusercontent.com/assets/7331408/6013360/949ea66e-ab21-11e4-9a04-af3dc34b40a1.PNG)
![capture2](https://cloud.githubusercontent.com/assets/7331408/6013362/9670474a-ab21-11e4-898f-df3599cc96b9.PNG)

**Comment by lobby417** [comment]
Those are sunbeams. Supposed to be used in daytime maps, but obviously irrelevant in night time maps. Will be removed in finalisation.
